/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    readonly "/healthz": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Check API health. */
        readonly get: operations["getHealth"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/auth/google/start": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Start Google sign-in.
         * @description Creates a short-lived signed OIDC attempt cookie and redirects the browser to Google.
         */
        readonly get: operations["startGoogleAuth"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/auth/google/callback": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Complete Google sign-in.
         * @description Validates the OIDC callback, creates an opaque browser session, and redirects to the configured web origin.
         */
        readonly get: operations["completeGoogleAuth"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/auth/session": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get the current browser session.
         * @description Returns authenticated identity state, or anonymous state when no valid session exists.
         */
        readonly get: operations["getAuthSession"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/auth/logout": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Revoke the current browser session. */
        readonly post: operations["logoutAuthSession"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/campuses/{slug}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Resolve a public campus by slug.
         * @description Returns the stable public identity needed to scope marketplace discovery.
         */
        readonly get: operations["getCampusBySlug"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/discovery": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Discover searchable rentable opportunities.
         * @description Returns flat search results — one row per property+unit type combination.
         *     Each result represents a "searchable rentable opportunity" with the best available pricing and offer count.
         *     By default, only unit types with at least one available agent offer are returned.
         *     This is the primary search interface for the public web app.
         */
        readonly get: operations["discover"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/properties": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List properties for a campus.
         * @description Returns campus-scoped properties ordered by newest first.
         *
         *     This is the initial discovery feed foundation. It intentionally returns properties, not a separate generic listing model.
         */
        readonly get: operations["listProperties"];
        readonly put?: never;
        /**
         * Create a property.
         * @description Creates a real-world accommodation property within a campus.
         */
        readonly post: operations["createProperty"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/properties/{id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get a property by ID. */
        readonly get: operations["getProperty"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/properties/{id}/unit-types": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List unit types for a property.
         * @description Returns property-level rentable unit types in creation order.
         */
        readonly get: operations["listPropertyUnitTypes"];
        readonly put?: never;
        /**
         * Create a unit type for a property.
         * @description Creates a property-level rentable unit type without tying it to a specific agent offer.
         */
        readonly post: operations["createPropertyUnitType"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/unit-types/{id}/agent-offers": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List agent offers for a unit type.
         * @description Returns agent-specific offers for a property unit type ordered by newest first.
         */
        readonly get: operations["listAgentOffers"];
        readonly put?: never;
        /**
         * Create an agent offer for a unit type.
         * @description Creates an agent-specific offer for a property unit type, including price and current availability status.
         */
        readonly post: operations["createAgentOffer"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/v1/media": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Upload media for a marketplace entity.
         * @description Uploads one or more image files for exactly one target: property, property unit type, or agent offer.
         *     Images are stored as originals and delivery variants are generated through Imgproxy URLs.
         */
        readonly post: operations["uploadMedia"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        readonly AuthUser: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            readonly email: string;
            readonly display_name: string;
            /** @enum {string} */
            readonly status: "active" | "suspended";
        };
        readonly AuthSessionResponse: {
            readonly authenticated: boolean;
            readonly user: components["schemas"]["AuthUser"] | null;
            readonly roles: readonly string[];
            readonly agent: null;
            /** @description CSRF token for unsafe requests when authenticated. */
            readonly csrf_token: string | null;
        };
        readonly HealthResponse: {
            /** @example ok */
            readonly status: string;
            /** @example development */
            readonly environment: string;
            /** @example dev */
            readonly version: string;
        };
        readonly Campus: {
            /** Format: uuid */
            readonly id: string;
            readonly slug: string;
            readonly name: string;
            readonly short_name: string;
        };
        readonly CampusResponse: {
            readonly campus: components["schemas"]["Campus"];
        };
        readonly CreatePropertyRequest: {
            /** Format: uuid */
            readonly campus_id: string;
            readonly name: string;
            readonly area: string;
            readonly landmark?: string;
            readonly description?: string;
        };
        readonly Property: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly campus_id: string;
            readonly name: string;
            readonly area: string;
            /** @description Approximate landmark. May be empty when unavailable. */
            readonly landmark: string;
            /** @description Building-level notes. May be empty when unavailable. */
            readonly description: string;
            /** @description Number of unit types at this property. */
            readonly unit_type_count: number;
            /** @description Number of currently available agent offers across all unit types. */
            readonly available_offer_count: number;
            /** @description Lowest price among available offers in whole Naira. 0 when no offers exist. */
            readonly lowest_price_naira: number;
            /**
             * Format: uri
             * @description Imgproxy-generated thumbnail URL for the first available image, when present.
             */
            readonly thumbnail_url?: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        readonly CreateUnitTypeRequest: {
            readonly category: components["schemas"]["UnitCategory"];
            /** @description Optional custom label. Defaults to the category display name (e.g. "Self-contained") when omitted. */
            readonly name?: string;
            readonly description?: string;
            /** @description Structural notes about the unit. Examples include "Kitchen is outside but private" or "Top floor corner unit." */
            readonly notes?: string;
            readonly bedroom_count?: number;
            readonly has_parlour?: boolean;
            readonly bathroom_type?: components["schemas"]["BathroomType"];
            readonly kitchen_type?: components["schemas"]["KitchenType"];
        };
        /** @enum {string} */
        readonly UnitCategory: "single_room" | "self_contained" | "room_and_parlour" | "one_bedroom_flat" | "two_bedroom_flat" | "three_bedroom_flat" | "other";
        /** @enum {string} */
        readonly BathroomType: "private" | "shared" | "unknown";
        /** @enum {string} */
        readonly KitchenType: "private" | "shared" | "none" | "unknown";
        readonly UnitType: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly property_id: string;
            readonly category: components["schemas"]["UnitCategory"];
            readonly name: string;
            /** @description Unit type description. May be empty when unavailable. */
            readonly description: string;
            /** @description Structural notes about the unit. Examples include "Kitchen is outside but private" or "Top floor corner unit." */
            readonly notes?: string | null;
            readonly bedroom_count: number | null;
            readonly has_parlour: boolean | null;
            readonly bathroom_type: components["schemas"]["BathroomType"] | null;
            readonly kitchen_type: components["schemas"]["KitchenType"] | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        readonly CreateAgentOfferRequest: {
            /** Format: uuid */
            readonly agent_id: string;
            readonly title: string;
            readonly description?: string;
            /** @description Operational notes about the offer. Examples include "2 left" or "Inspection tomorrow only." */
            readonly notes?: string;
            readonly price_naira: number;
            /**
             * @default available
             * @enum {string}
             */
            readonly status: "available" | "unavailable" | "paused";
        };
        readonly AgentOffer: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly property_unit_type_id: string;
            /** Format: uuid */
            readonly agent_id: string;
            readonly title: string;
            /** @description Agent-specific offer description. May be empty when unavailable. */
            readonly description: string;
            /** @description Operational notes about the offer. Examples include "2 left" or "Inspection tomorrow only." */
            readonly notes?: string | null;
            readonly price_naira: number;
            /** @enum {string} */
            readonly status: "available" | "unavailable" | "paused";
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        readonly AgentSummary: {
            /** Format: uuid */
            readonly id: string;
            readonly display_name: string;
        };
        readonly AgentOfferDetail: components["schemas"]["AgentOffer"] & {
            readonly agent: components["schemas"]["AgentSummary"];
            readonly media: readonly components["schemas"]["Media"][];
        };
        readonly UnitTypeDetail: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly property_id: string;
            readonly category: components["schemas"]["UnitCategory"];
            readonly name: string;
            /** @description Unit type description. May be empty when unavailable. */
            readonly description: string;
            /** @description Structural notes about the unit. */
            readonly notes?: string | null;
            readonly bedroom_count: number | null;
            readonly has_parlour: boolean | null;
            readonly bathroom_type: components["schemas"]["BathroomType"] | null;
            readonly kitchen_type: components["schemas"]["KitchenType"] | null;
            readonly agent_offers: readonly components["schemas"]["AgentOfferDetail"][];
            readonly media: readonly components["schemas"]["Media"][];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        readonly PropertyDetail: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly campus_id: string;
            readonly name: string;
            readonly area: string;
            /** @description Approximate landmark. May be empty when unavailable. */
            readonly landmark: string;
            /** @description Building-level notes. May be empty when unavailable. */
            readonly description: string;
            readonly unit_types: readonly components["schemas"]["UnitTypeDetail"][];
            readonly media: readonly components["schemas"]["Media"][];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        readonly PropertyResponse: {
            readonly property: components["schemas"]["Property"];
        };
        readonly PropertyDetailResponse: {
            readonly property: components["schemas"]["PropertyDetail"];
        };
        readonly DiscoveryResponse: {
            readonly results: readonly components["schemas"]["DiscoveryResult"][];
            readonly metadata: components["schemas"]["Metadata"];
        };
        readonly DiscoveryResult: {
            readonly property: {
                /** Format: uuid */
                readonly id: string;
                readonly name: string;
                readonly area: string;
                readonly landmark?: string | null;
            };
            readonly unit_type: {
                /** Format: uuid */
                readonly id: string;
                readonly category: components["schemas"]["UnitCategory"];
                readonly name: string;
                readonly description?: string | null;
                readonly notes?: string | null;
                readonly bedroom_count?: number | null;
                readonly has_parlour?: boolean | null;
                readonly bathroom_type?: components["schemas"]["BathroomType"] | null;
                readonly kitchen_type?: components["schemas"]["KitchenType"] | null;
            };
            readonly pricing: {
                /** @description Lowest available price in whole Naira, or null when no offer is available. */
                readonly lowest_price_naira: number | null;
            };
            readonly offer_summary: {
                readonly available_offer_count: number;
            };
            /** Format: uri */
            readonly thumbnail_url?: string | null;
            /**
             * @description Source layer for the discovery thumbnail. `property` is contextual fallback media, not a claim about the exact unit.
             * @enum {string}
             */
            readonly thumbnail_source: "unit_type" | "property" | "none";
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        readonly Media: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly property_id?: string | null;
            /** Format: uuid */
            readonly property_unit_type_id?: string | null;
            /** Format: uuid */
            readonly agent_offer_id?: string | null;
            /** Format: uuid */
            readonly uploaded_by_agent_id?: string | null;
            /**
             * Format: uri
             * @description Public URL for the original stored object.
             */
            readonly url: string;
            /**
             * Format: uri
             * @description Imgproxy-generated thumbnail URL.
             */
            readonly thumbnail_url: string;
            /**
             * Format: uri
             * @description Imgproxy-generated medium-size URL.
             */
            readonly medium_url: string;
            /** @enum {string} */
            readonly kind: "image" | "video";
            readonly caption?: string | null;
            /** @example image/jpeg */
            readonly content_type?: string | null;
            readonly size_bytes: number;
            /** Format: date-time */
            readonly created_at: string;
        };
        readonly MediaUploadResponse: {
            readonly media: readonly components["schemas"]["Media"][];
        };
        readonly PropertiesResponse: {
            readonly properties: readonly components["schemas"]["Property"][];
            readonly metadata: components["schemas"]["Metadata"];
        };
        readonly Metadata: {
            readonly current_page: number;
            readonly page_size: number;
            readonly first_page: number;
            readonly last_page: number;
            readonly total_records: number;
        };
        readonly UnitTypeResponse: {
            readonly unit_type: components["schemas"]["UnitType"];
        };
        readonly UnitTypesResponse: {
            readonly unit_types: readonly components["schemas"]["UnitType"][];
        };
        readonly AgentOfferResponse: {
            readonly agent_offer: components["schemas"]["AgentOffer"];
        };
        readonly AgentOffersResponse: {
            readonly agent_offers: readonly components["schemas"]["AgentOffer"][];
        };
        readonly Error: {
            /**
             * @example bad_request
             * @example validation_failed
             * @example not_found
             * @example method_not_allowed
             * @example internal_server_error
             */
            readonly code: string;
            readonly message: string;
        };
        readonly ValidationError: components["schemas"]["Error"] & {
            readonly fields: {
                readonly [key: string]: string;
            };
        };
        readonly ErrorResponse: {
            readonly error: components["schemas"]["Error"];
        };
        readonly ValidationErrorResponse: {
            readonly error: components["schemas"]["ValidationError"];
        };
    };
    responses: {
        /** @description Request body or syntax is invalid. */
        readonly BadRequest: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request validation failed. */
        readonly ValidationFailed: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ValidationErrorResponse"];
            };
        };
        /** @description Resource was not found. */
        readonly NotFound: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description HTTP method is not supported for this resource. */
        readonly MethodNotAllowed: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Server encountered an unexpected problem. */
        readonly InternalServerError: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication is not configured for this environment. */
        readonly AuthUnavailable: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The Google sign-in callback is invalid or expired. */
        readonly InvalidAuthCallback: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Authentication is required or the session is invalid. */
        readonly Unauthenticated: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request is not allowed. */
        readonly Forbidden: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description CSRF token returned by the authenticated session endpoint. */
        readonly CSRFToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly getHealth: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description API is healthy. */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["HealthResponse"];
                };
            };
            readonly 405: components["responses"]["MethodNotAllowed"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly startGoogleAuth: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Redirect to Google sign-in. */
            readonly 302: {
                headers: {
                    readonly Location?: string;
                    readonly "Set-Cookie"?: string;
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            readonly 503: components["responses"]["AuthUnavailable"];
        };
    };
    readonly completeGoogleAuth: {
        readonly parameters: {
            readonly query?: {
                readonly code?: string;
                readonly state?: string;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Redirect to the configured web origin after successful sign-in. */
            readonly 302: {
                headers: {
                    readonly Location?: string;
                    readonly "Set-Cookie"?: string;
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            readonly 400: components["responses"]["InvalidAuthCallback"];
            readonly 500: components["responses"]["InternalServerError"];
            readonly 503: components["responses"]["AuthUnavailable"];
        };
    };
    readonly getAuthSession: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Current session state. */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly logoutAuthSession: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description CSRF token returned by the authenticated session endpoint. */
                readonly "X-CSRF-Token": components["parameters"]["CSRFToken"];
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Session revoked and browser cookies cleared. */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            readonly 401: components["responses"]["Unauthenticated"];
            readonly 403: components["responses"]["Forbidden"];
            readonly 500: components["responses"]["InternalServerError"];
            readonly 503: components["responses"]["AuthUnavailable"];
        };
    };
    readonly getCampusBySlug: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                /** @description Stable campus slug, such as `futa`. */
                readonly slug: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Campus returned successfully. */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["CampusResponse"];
                };
            };
            readonly 404: components["responses"]["NotFound"];
            readonly 422: components["responses"]["ValidationFailed"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly discover: {
        readonly parameters: {
            readonly query: {
                /** @description Campus ID that scopes marketplace discovery. */
                readonly campus_id: string;
                /**
                 * @description Filter by unit type category. Accepts a single category or comma-separated list.
                 *     Examples: `self_contained`, `self_contained,single_room`
                 */
                readonly category?: string;
                /**
                 * @description Search property names, areas, landmarks, and unit type names.
                 *     Matching is case-insensitive and combines with the other discovery filters.
                 */
                readonly q?: string;
                /**
                 * @description Filter by area text. Case-insensitive partial match (ILIKE).
                 *     Example: `area=South` matches "South Gate", "South Campus".
                 */
                readonly area?: string;
                /** @description Filter by bathroom type. */
                readonly bathroom_type?: components["schemas"]["BathroomType"];
                /** @description Filter by kitchen type. */
                readonly kitchen_type?: components["schemas"]["KitchenType"];
                /** @description Filter by whether the unit has a parlour/living room. */
                readonly has_parlour?: boolean;
                /** @description Minimum price in naira. */
                readonly min_price?: number;
                /** @description Maximum price in naira. */
                readonly max_price?: number;
                /** @description Return only opportunities with an available offer, or include all unit types. */
                readonly availability?: "available" | "all";
                /** @description Page number. Defaults to 1. */
                readonly page?: number;
                /** @description Number of items per page. Defaults to 20. Maximum is 100. */
                readonly page_size?: number;
                /**
                 * @description Sort order. `recommended` uses deterministic availability, usable image media,
                 *     completeness, recent activity, available-offer count, and stable-ID ordering.
                 *     Prefix supported fields with `-` for descending.
                 */
                readonly sort?: "recommended" | "created_at" | "-created_at" | "lowest_price_naira" | "-lowest_price_naira";
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Discovery results returned successfully. */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["DiscoveryResponse"];
                };
            };
            readonly 422: components["responses"]["ValidationFailed"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly listProperties: {
        readonly parameters: {
            readonly query: {
                /** @description Campus ID that scopes marketplace discovery. */
                readonly campus_id: string;
                /** @description Page number. Defaults to 1. */
                readonly page?: number;
                /** @description Number of items per page. Defaults to 20. Maximum is 100. */
                readonly page_size?: number;
                /** @description Sort order. Prefix with `-` for descending. Defaults to `-created_at`. */
                readonly sort?: "created_at" | "-created_at" | "name" | "-name" | "area" | "-area" | "lowest_price_naira" | "-lowest_price_naira" | "available_offer_count" | "-available_offer_count";
                /** @description Filter by area text (case-insensitive partial match). */
                readonly area?: string;
                /** @description Filter by property name (case-insensitive partial match). */
                readonly name?: string;
                /** @description Filter to properties that have at least one available agent offer. Accepts `true` or `false`. */
                readonly has_offers?: boolean;
                /** @description Minimum price in naira. Filters by the property's lowest available offer price. */
                readonly min_price?: number;
                /** @description Maximum price in naira. Filters by the property's lowest available offer price. */
                readonly max_price?: number;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Properties returned successfully. */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PropertiesResponse"];
                };
            };
            readonly 422: components["responses"]["ValidationFailed"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly createProperty: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["CreatePropertyRequest"];
            };
        };
        readonly responses: {
            /** @description Property created successfully. */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PropertyResponse"];
                };
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 422: components["responses"]["ValidationFailed"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly getProperty: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                /** @description Property ID. */
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Property returned successfully. */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["PropertyDetailResponse"];
                };
            };
            readonly 404: components["responses"]["NotFound"];
            readonly 422: components["responses"]["ValidationFailed"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly listPropertyUnitTypes: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                /** @description Property ID. */
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Unit types returned successfully. */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["UnitTypesResponse"];
                };
            };
            readonly 404: components["responses"]["NotFound"];
            readonly 422: components["responses"]["ValidationFailed"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly createPropertyUnitType: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                /** @description Property ID. */
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["CreateUnitTypeRequest"];
            };
        };
        readonly responses: {
            /** @description Unit type created successfully. */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["UnitTypeResponse"];
                };
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 404: components["responses"]["NotFound"];
            readonly 422: components["responses"]["ValidationFailed"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly listAgentOffers: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                /** @description Unit type ID. */
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Agent offers returned successfully. */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AgentOffersResponse"];
                };
            };
            readonly 404: components["responses"]["NotFound"];
            readonly 422: components["responses"]["ValidationFailed"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly createAgentOffer: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                /** @description Unit type ID. */
                readonly id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["CreateAgentOfferRequest"];
            };
        };
        readonly responses: {
            /** @description Agent offer created successfully. */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AgentOfferResponse"];
                };
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 404: components["responses"]["NotFound"];
            readonly 422: components["responses"]["ValidationFailed"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
    readonly uploadMedia: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "multipart/form-data": {
                    /** @description One or more JPEG, PNG, or WebP image files. */
                    readonly files: readonly string[];
                    /**
                     * Format: uuid
                     * @description Property target ID. Use exactly one target field.
                     */
                    readonly property_id?: string;
                    /**
                     * Format: uuid
                     * @description Property unit type target ID. Use exactly one target field.
                     */
                    readonly property_unit_type_id?: string;
                    /**
                     * Format: uuid
                     * @description Agent offer target ID. Use exactly one target field.
                     */
                    readonly agent_offer_id?: string;
                    /**
                     * Format: uuid
                     * @description Uploading agent ID. This is explicit until authenticated agent context exists.
                     */
                    readonly uploaded_by_agent_id: string;
                    readonly caption?: string;
                };
            };
        };
        readonly responses: {
            /** @description Media uploaded successfully. */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["MediaUploadResponse"];
                };
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 404: components["responses"]["NotFound"];
            readonly 422: components["responses"]["ValidationFailed"];
            readonly 500: components["responses"]["InternalServerError"];
        };
    };
}
