/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesPropertyIdRouteImport } from './routes/properties.$propertyId'
import { Route as PropertiesPropertyIdUnitTypesUnitTypeIdRouteImport } from './routes/properties.$propertyId_.unit-types.$unitTypeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesPropertyIdRoute = PropertiesPropertyIdRouteImport.update({
  id: '/properties/$propertyId',
  path: '/properties/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesPropertyIdUnitTypesUnitTypeIdRoute =
  PropertiesPropertyIdUnitTypesUnitTypeIdRouteImport.update({
    id: '/properties/$propertyId_/unit-types/$unitTypeId',
    path: '/properties/$propertyId/unit-types/$unitTypeId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/properties/$propertyId/unit-types/$unitTypeId': typeof PropertiesPropertyIdUnitTypesUnitTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/properties/$propertyId/unit-types/$unitTypeId': typeof PropertiesPropertyIdUnitTypesUnitTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/properties/$propertyId': typeof PropertiesPropertyIdRoute
  '/properties/$propertyId_/unit-types/$unitTypeId': typeof PropertiesPropertyIdUnitTypesUnitTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/properties/$propertyId'
    | '/properties/$propertyId/unit-types/$unitTypeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/properties/$propertyId'
    | '/properties/$propertyId/unit-types/$unitTypeId'
  id:
    | '__root__'
    | '/'
    | '/properties/$propertyId'
    | '/properties/$propertyId_/unit-types/$unitTypeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PropertiesPropertyIdRoute: typeof PropertiesPropertyIdRoute
  PropertiesPropertyIdUnitTypesUnitTypeIdRoute: typeof PropertiesPropertyIdUnitTypesUnitTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$propertyId': {
      id: '/properties/$propertyId'
      path: '/properties/$propertyId'
      fullPath: '/properties/$propertyId'
      preLoaderRoute: typeof PropertiesPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/$propertyId_/unit-types/$unitTypeId': {
      id: '/properties/$propertyId_/unit-types/$unitTypeId'
      path: '/properties/$propertyId/unit-types/$unitTypeId'
      fullPath: '/properties/$propertyId/unit-types/$unitTypeId'
      preLoaderRoute: typeof PropertiesPropertyIdUnitTypesUnitTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PropertiesPropertyIdRoute: PropertiesPropertyIdRoute,
  PropertiesPropertyIdUnitTypesUnitTypeIdRoute:
    PropertiesPropertyIdUnitTypesUnitTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
